// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvmlAEuqHcriCB5xSvOyMRDqjNRbkgPE8',
    appId: '1:249177044092:web:79073b201a19a9a6a305f9',
    messagingSenderId: '249177044092',
    projectId: 'plant-deases-f4df2',
    authDomain: 'plant-deases-f4df2.firebaseapp.com',
    storageBucket: 'plant-deases-f4df2.appspot.com',
    measurementId: 'G-54YRBPX5CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATnrB9ucQCN-MNT3C2WS1koH8J_vUzfVI',
    appId: '1:249177044092:android:e533f120cc9bb142a305f9',
    messagingSenderId: '249177044092',
    projectId: 'plant-deases-f4df2',
    storageBucket: 'plant-deases-f4df2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo4_rNIIDKszPZAdrv3hiEK_3WgrXk7kY',
    appId: '1:249177044092:ios:63b322fc7a00ec5aa305f9',
    messagingSenderId: '249177044092',
    projectId: 'plant-deases-f4df2',
    storageBucket: 'plant-deases-f4df2.appspot.com',
    iosBundleId: 'com.example.plantDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo4_rNIIDKszPZAdrv3hiEK_3WgrXk7kY',
    appId: '1:249177044092:ios:63b322fc7a00ec5aa305f9',
    messagingSenderId: '249177044092',
    projectId: 'plant-deases-f4df2',
    storageBucket: 'plant-deases-f4df2.appspot.com',
    iosBundleId: 'com.example.plantDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvmlAEuqHcriCB5xSvOyMRDqjNRbkgPE8',
    appId: '1:249177044092:web:9964bfc92e06a5b3a305f9',
    messagingSenderId: '249177044092',
    projectId: 'plant-deases-f4df2',
    authDomain: 'plant-deases-f4df2.firebaseapp.com',
    storageBucket: 'plant-deases-f4df2.appspot.com',
    measurementId: 'G-YYEQK9SK9G',
  );
}
